import type { InternalState } from "../../src/types";
import { normalizeMaintainVisibleContentPosition } from "../../src/utils/normalizeMaintainVisibleContentPosition";

export const DEFAULT_CONTENT_INSET = { bottom: 0, left: 0, right: 0, top: 0 };

export function createMockState(
    overrides: Partial<Omit<InternalState, "props"> & { props: Partial<InternalState["props"]> }> = {},
): InternalState {
    return {
        // Required by UpdateItemPositions
        averageSizes: {},
        columnSpans: new Map(),
        // Core calculateItemsInView properties
        columns: new Map(),
        containerItemKeys: new Map(),
        containerItemTypes: new Map(),
        contentInsetOverride: undefined,
        dataChangeNeedsScrollUpdate: false,
        enableScrollForNextCalculateItemsInView: true,
        // Required by Pick types from dependencies
        endBuffered: 0,
        endNoBuffer: 0,
        endReachedSnapshot: undefined,
        firstFullyOnScreenIndex: 0,
        idCache: [],
        idsInView: [],
        ignoreScrollFromMVCP: undefined,
        ignoreScrollFromMVCPIgnored: false,
        ignoreScrollFromMVCPTimeout: undefined,
        indexByKey: new Map(),
        initialAnchor: undefined,
        initialScroll: undefined,
        isAtEnd: false,
        isAtStart: false,
        isEndReached: null,
        isStartReached: null,
        lastBatchingAction: 0,
        lastLayout: undefined,
        // Required by CheckAtBottom and SetDidLayout
        loadStartTime: Date.now(),
        maintainingScrollAtEnd: false,
        minIndexSizeChanged: undefined,
        nativeContentInset: undefined,
        nativeMarginTop: 0,
        otherAxisSize: undefined,
        positions: new Map(),
        queuedCalculateItemsInView: undefined,
        queuedInitialLayout: false,
        refScroller: undefined as any,
        scroll: 0,
        scrollAdjustHandler: {
            getAdjust: () => 0,
            requestAdjust: () => {}, // Mock scroll adjust handler
            setMounted: () => {},
        },
        scrollForNextCalculateItemsInView: undefined,
        scrollHistory: [],
        // Required by PrepareMVCP
        scrollLength: 300,
        scrollPending: 0,
        scrollPrev: 0,
        scrollPrevTime: 0,
        scrollTime: 0,
        sizes: new Map(),
        sizesKnown: new Map(),
        startBuffered: 0,
        startBufferedId: undefined,
        startNoBuffer: 0,
        startReachedSnapshot: undefined,
        // Sticky container setup (empty by default)
        stickyContainerPool: new Set(),
        stickyContainers: new Map(),
        timeoutSetPaddingTop: undefined,
        timeoutSizeMessage: undefined,
        timeouts: new Set(),
        totalSize: 1000,
        triggerCalculateItemsInView: () => {},
        viewabilityConfigCallbackPairs: undefined,
        ...overrides,
        props: {
            alignItemsAtEnd: false,
            alwaysRender: undefined,
            alwaysRenderIndicesArr: [],
            alwaysRenderIndicesSet: new Set<number>(),
            contentInset: DEFAULT_CONTENT_INSET,
            data: [],
            dataVersion: undefined,
            drawDistance: 100,
            estimatedItemSize: undefined,
            getEstimatedItemSize: undefined,
            getFixedItemSize: undefined,
            getItemType: undefined,
            horizontal: false,
            initialContainerPoolRatio: 2,
            initialScroll: undefined,
            itemsAreEqual: undefined,
            keyExtractor: (_: any, index: number) => `item_${index}`,
            maintainScrollAtEnd: false,
            maintainScrollAtEndThreshold: 0.1,
            maintainVisibleContentPosition: normalizeMaintainVisibleContentPosition(undefined),
            numColumns: 1,
            onEndReached: undefined,
            onEndReachedThreshold: 0.1,
            onItemSizeChanged: undefined,
            onLoad: undefined,
            onScroll: undefined,
            onStartReached: undefined,
            onStartReachedThreshold: 0.1,
            overrideItemLayout: undefined,
            recycleItems: false,
            renderItem: undefined,
            snapToIndices: undefined,
            stickyIndicesArr: [],
            // Provide empty sticky indices for tests by default
            stickyIndicesSet: new Set<number>(),
            stylePaddingBottom: undefined,
            stylePaddingTop: 0,
            suggestEstimatedItemSize: false,
            ...(overrides.props ?? {}),
        },
    } as unknown as InternalState;
}
